/**
 * Where the round lives on chain.
 *
 * GENERATED by `scripts/deploy.mjs`. Editing it by hand only guarantees it
 * disagrees with the chain — redeploy instead.
 */

export type Deployment = {
  network: "sepolia" | "mainnet";
  rpc: string;
  chainId: string;
  round: string;
  escrow: string | null;
};

export const DEPLOYMENT: Deployment | null = {
  network: "sepolia",
  rpc: "https://starknet-sepolia-rpc.publicnode.com",
  chainId: "0x534e5f5345504f4c4941",
  round: "0x252ecaea30b870d8ab30075ac7eb4b6e29572dbd0c0464be33396497026756d",
  escrow: "0x7c12b8419a68a412f9397e16e23faf3219b0a547e70e141fff87a295c311ad8",
};
