/**
 * Where the round lives on chain.
 *
 * GENERATED by `scripts/deploy.mjs`. Editing it by hand only guarantees it
 * disagrees with the chain — redeploy instead.
 */

export type Deployment = {
  network: "sepolia" | "mainnet";
  rpc: string;
  chainId: string;
  round: string;
  escrow: string | null;
};

export const DEPLOYMENT: Deployment | null = {
  network: "sepolia",
  rpc: "https://starknet-sepolia-rpc.publicnode.com",
  chainId: "0x534e5f5345504f4c4941",
  round: "0x7ba794c5341f60b9aa2ae0435221d82cef3c611be0b78280579872cbe8df74",
  escrow: "0x60a3298a7ecf2a61ad1cfa84942e2af932a0b4db0bf235b07d10c11e737427b",
};
