/**
 * Where the round lives on chain.
 *
 * GENERATED by `scripts/deploy.mjs`. Editing it by hand only guarantees it
 * disagrees with the chain — redeploy instead.
 */

export type Deployment = {
  network: "sepolia" | "mainnet";
  rpc: string;
  chainId: string;
  round: string;
  escrow: string | null;
};

export const DEPLOYMENT: Deployment | null = {
  network: "mainnet",
  rpc: "https://starknet-rpc.publicnode.com",
  chainId: "0x534e5f4d41494e",
  round: "0x13ea00a52a5dc531430b4ddc492d2c9da8c187b7a49d96c86df2771c301d9ce",
  escrow: "0x21006bb87b736db531088782b42ad7eb9d37d1f373c438634625bbe484275cf",
};
